import type { Dossier, DossierSlide } from "../schema/types";
import { withExampleClaims } from "./example-claims";
import { neutralAssetRegistry } from "./neutral-asset-registry";
import {
  neutralPageMarker,
  neutralProofImage,
  neutralRiskImage,
  neutralStoryboardImage,
  neutralStudioPortrait,
} from "./neutral-assets";
import { exampleTheme } from "./example-theme";

export const exampleDossier = {
  meta: {
    title: "Un système de récit pour Prospect Démo",
    client: "Prospect Démo",
    frameworkProfile: "neutral",
    studio: "Studio Démo",
    language: "fr-CH",
    version: "1.0",
    date: "2026-07-18",
    distributionMode: "private-prospecting",
    relationshipStatus: "independent-proposal",
    generativeAssets: "forbidden",
    stage: "final",
    forbiddenClientTerms: ["client officiel", "mandaté par Prospect Démo", "partenariat approuvé"],
    confidential: true,
  },
  evidence: [
    { id: "fixture:context-audit", kind: "observation", status: "verified", claim: "Signaux fictifs consignés dans la note de cadrage locale de cette démonstration." },
    { id: "fixture:vector-assets", kind: "fact", status: "verified", claim: "Visuels SVG neutres fabriqués localement et inclus avec le moteur." },
    { id: "fixture:contact-card", kind: "fact", status: "verified", claim: "Coordonnées fictives définies dans la fixture locale de démonstration." },
  ],
  assets: neutralAssetRegistry,
  theme: exampleTheme,
  slides: ([
    {
      id: "01-ouverture",
      type: "cover",
      tone: "ink",
      client: "Prospect Démo",
      title: "De la matière au mouvement",
      subtitle: "Un territoire narratif capable de rendre une expertise visible, désirable et mémorable.",
      proposition: "Plateforme de récit, films de marque et système d'activation",
      tag: "Proposition créative",
      relationshipLabel: "Proposition indépendante pour Prospect Démo, par Studio Démo",
      motifState: "full",
    },
    {
      id: "02-architecture",
      type: "architecture",
      eyebrow: "Architecture du récit",
      title: "Transformer des preuves en préférence",
      statement: "Le système relie ce que la marque sait faire, ce qu'elle montre et ce que le public retient.",
      nodes: [
        { label: "Matière", detail: "Gestes, lieux, personnes, détails et décisions.", kind: "input" },
        { label: "Point de vue", detail: "Une idée directrice qui ordonne toutes les preuves.", kind: "core" },
        { label: "Formats", detail: "Films, récits courts, objets éditoriaux et rendez-vous.", kind: "core" },
        { label: "Mémoire", detail: "Des signes distinctifs répétés avec discipline.", kind: "output" },
      ],
      axisLabel: "Substance → mise en scène → reconnaissance",
      image: neutralProofImage,
      chapterMark: neutralPageMarker,
      motifState: "quiet",
    },
    {
      id: "03-pourquoi-maintenant",
      type: "three-columns",
      variant: "why-now",
      eyebrow: "Pourquoi maintenant",
      title: "Trois signaux convergent",
      intro: "La marque possède déjà la substance. L'enjeu consiste à lui donner une forme qui circule.",
      columns: [
        { title: "Attention fragmentée", body: "Les publics arbitrent en quelques secondes. La singularité doit être lisible immédiatement.", signal: "Contexte" },
        { title: "Preuves dispersées", body: "Le savoir-faire existe, mais il apparaît comme une addition de projets plutôt qu'un système.", signal: "Tension" },
        { title: "Ambition commune", body: "Une direction claire peut aligner vente, recrutement, partenariats et culture interne.", signal: "Levier" },
      ],
      conclusion: "Le bon récit ne décore pas l'activité. Il en révèle la logique.",
    },
    {
      id: "04-preuves",
      type: "proof",
      tone: "surface",
      eyebrow: "Démonstration neutre",
      title: "Des preuves à construire avant de les affirmer",
      proofPoints: [
        "Démonstration: documenter un cas avec son contexte et ses limites.",
        "Démonstration: relier une promesse à un résultat observable.",
        "Démonstration: attribuer chaque fait à une source vérifiable.",
      ],
      image: neutralProofImage,
      motifState: "full",
    },
    {
      id: "05-manifeste",
      type: "manifesto",
      tone: "accent",
      title: "Nous ne montrons pas seulement ce qui est fait.",
      lines: [
        "Nous montrons pourquoi chaque choix compte.",
        "Nous rapprochons la précision du quotidien.",
        "Nous donnons un visage aux exigences invisibles.",
        "Nous faisons de la retenue une force reconnaissable.",
      ],
      closing: "La marque devient un regard, pas une collection de messages.",
      motifState: "hidden",
    },
    {
      id: "06-risque",
      type: "risk",
      tone: "ink",
      eyebrow: "Risque d'inaction",
      title: "Rester excellent ne suffit pas à être choisi",
      lead: "Sans système commun, chaque prise de parole recommence à zéro et dilue la valeur perçue.",
      risks: [
        { label: "Interchangeabilité", consequence: "Les preuves techniques se ressemblent et la comparaison glisse vers le prix.", severity: 3 },
        { label: "Dispersion", consequence: "Les canaux racontent des histoires différentes, sans effet cumulatif.", severity: 2 },
        { label: "Dépendance", consequence: "La marque reste tributaire des explications individuelles de quelques personnes.", severity: 2 },
      ],
      counterpoint: "La cohérence éditoriale transforme chaque contenu en actif de marque.",
      image: neutralRiskImage,
      motifState: "quiet",
    },
    {
      id: "07-basculements",
      type: "opportunity",
      variant: "shifts",
      eyebrow: "Basculements",
      title: "Faire évoluer la perception, pas seulement la communication",
      shifts: [
        { from: "Un catalogue de réalisations", to: "Un point de vue propriétaire", implication: "Chaque projet renforce la même idée de marque." },
        { from: "Des contenus ponctuels", to: "Une matière éditoriale continue", implication: "La production gagne en rythme et en rendement." },
        { from: "Une expertise expliquée", to: "Une expertise ressentie", implication: "L'émotion accélère la compréhension et la préférence." },
      ],
    },
    {
      id: "08-systeme",
      type: "platform",
      variant: "system",
      tone: "surface",
      eyebrow: "Système de marque",
      title: "Une idée centrale, quatre couches d'expression",
      core: { label: "La précision en mouvement", detail: "Le geste exact devient le fil rouge du récit." },
      layers: [
        { label: "Langage", detail: "Des phrases courtes, concrètes, ancrées dans les décisions." },
        { label: "Image", detail: "Matières franches, cadrages serrés, présence humaine sans pose." },
        { label: "Rythme", detail: "Alternance de calme, de tension et de révélations précises." },
        { label: "Preuve", detail: "Chaque promesse débouche sur un fait observable." },
      ],
      outcomes: ["Reconnaissance", "Cohérence", "Réutilisation"],
    },
    {
      id: "09-methode",
      type: "timeline",
      variant: "method",
      eyebrow: "Méthode",
      title: "Quatre temps, un seul fil directeur",
      steps: [
        { phase: "Cadrer", duration: "S1", title: "Trouver la tension", detail: "Entretiens, audit et sélection des preuves décisives.", deliverable: "Carte narrative" },
        { phase: "Écrire", duration: "S2", title: "Fixer le regard", detail: "Concept, manifeste, langage et architecture des formats.", deliverable: "Plateforme de récit" },
        { phase: "Produire", duration: "S3 à S5", title: "Créer la matière", detail: "Tournage modulaire et fabrication des actifs prioritaires.", deliverable: "Master et déclinaisons" },
        { phase: "Activer", duration: "S6", title: "Installer le rythme", detail: "Orchestration des canaux et guide de continuité.", deliverable: "Plan 90 jours" },
      ],
    },
    {
      id: "10-film-hero",
      type: "film-concept",
      tone: "ink",
      eyebrow: "Film 01",
      title: "Le film manifeste",
      conceptName: "Avant que cela paraisse simple",
      logline: "Une succession de décisions invisibles précède chaque geste évident. Le film révèle cette précision cachée.",
      format: "Film de marque",
      duration: "75 secondes",
      toneWords: ["Tactile", "Tendu", "Humain", "Précis"],
      image: neutralProofImage,
    },
    {
      id: "11-storyboard-hero",
      type: "storyboard",
      eyebrow: "Film 01",
      title: "Une montée de la matière vers l'évidence",
      frames: [
        { number: "01", beat: "Silence", visual: "Plans presque abstraits de surfaces, de lumière et de mains immobiles.", onScreen: "Tout commence avant le geste.", audio: "Souffle du lieu.", image: neutralStoryboardImage("01", "Silence") },
        { number: "02", beat: "Tension", visual: "Mesures, essais, reprises. Les choix s'enchaînent sans explication.", audio: "Percussions sèches.", image: neutralStoryboardImage("02", "Tension") },
        { number: "03", beat: "Mouvement", visual: "Les gestes se répondent, l'espace prend forme et le rythme s'accélère.", onScreen: "La précision en mouvement.", image: neutralStoryboardImage("03", "Mouvement") },
        { number: "04", beat: "Évidence", visual: "Un plan large révèle le résultat, calme et parfaitement lisible.", audio: "Retour au silence.", image: neutralStoryboardImage("04", "Évidence") },
      ],
    },
    {
      id: "12-film-serie",
      type: "film-concept",
      tone: "signal",
      eyebrow: "Film 02",
      title: "La série de preuves",
      conceptName: "Une décision, un impact",
      logline: "Chaque épisode isole un choix concret et montre, en moins d'une minute, ce qu'il change réellement.",
      format: "Série verticale et horizontale",
      duration: "6 × 35 secondes",
      toneWords: ["Direct", "Documentaire", "Sériel", "Utile"],
      image: neutralRiskImage,
    },
    {
      id: "13-storyboard-serie",
      type: "storyboard",
      eyebrow: "Film 02",
      title: "Un format répétable, pensé pour durer",
      duration: "3 min 20 s",
      frames: [
        { number: "01", timecode: "00:00-00:18", beat: "Question", visual: "Une contrainte réelle apparaît en texte sur une image très simple.", onScreen: "Pourquoi ce détail?", image: neutralStoryboardImage("01", "Question") },
        { number: "02", timecode: "00:18-00:38", beat: "Décision", visual: "Une personne explique le choix en une phrase, face au travail en cours.", audio: "Voix directe.", image: neutralStoryboardImage("02", "Décision") },
        { number: "03", timecode: "00:38-00:58", beat: "Démonstration", visual: "Le geste et son effet sont montrés sans artifice.", onScreen: "Voici ce que cela change.", image: neutralStoryboardImage("03", "Démonstration") },
        { number: "04", timecode: "00:58-01:18", beat: "Signature", visual: "Le même cadre final clôt chaque épisode et construit la reconnaissance.", audio: "Signature sonore.", image: neutralStoryboardImage("04", "Signature") },
        { number: "05", timecode: "01:18-01:38", beat: "Contrainte", visual: "Une nouvelle situation ouvre un second cycle de démonstration.", image: neutralStoryboardImage("05", "Contrainte") },
        { number: "06", timecode: "01:38-01:58", beat: "Réponse", visual: "Le choix est formulé en une phrase immédiatement vérifiable.", image: neutralStoryboardImage("06", "Réponse") },
        { number: "07", timecode: "01:58-02:18", beat: "Détail", visual: "Un plan rapproché isole le geste qui fait la différence.", image: neutralStoryboardImage("07", "Détail") },
        { number: "08", timecode: "02:18-02:38", beat: "Effet", visual: "Le résultat est montré dans son contexte d'usage réel.", image: neutralStoryboardImage("08", "Effet") },
        { number: "09", timecode: "02:38-02:58", beat: "Transmission", visual: "Une personne relie la décision à son impact collectif.", image: neutralStoryboardImage("09", "Transmission") },
        { number: "10", timecode: "02:58-03:20", beat: "Système", visual: "Les épisodes se rassemblent sous une signature commune.", image: neutralStoryboardImage("10", "Système") },
      ],
    },
    {
      id: "14-activation",
      type: "activation",
      eyebrow: "Activation",
      title: "Un tournage, plusieurs vies",
      lead: "La matière est captée dès l'origine pour alimenter un système cohérent pendant trois mois.",
      channels: [
        { name: "Site", role: "Installer la promesse", asset: "Film hero + chapitres de preuve" },
        { name: "Réseaux", role: "Créer la répétition", asset: "Série courte + extraits matière" },
        { name: "Vente", role: "Accélérer la confiance", asset: "Séquences par objection" },
        { name: "Interne", role: "Aligner les équipes", asset: "Manifeste + kit de langage" },
      ],
      sequence: ["Révéler", "Prouver", "Répéter", "Approfondir"],
    },
    {
      id: "15-production",
      type: "production",
      tone: "surface",
      eyebrow: "Production",
      title: "Une fabrication compacte et maîtrisée",
      lead: "Chaque journée de production est conçue comme une récolte de matière, pas comme un livrable isolé.",
      workstreams: [
        { name: "Narration", detail: "Concept, scripts, interviews et continuité éditoriale.", owner: "Direction" },
        { name: "Image", detail: "Repérage, tournage, photographie et banque de plans.", owner: "Production" },
        { name: "Déclinaisons", detail: "Montages, formats courts, sous-titres et exports canaux.", owner: "Postproduction" },
      ],
      deliverables: ["1 film manifeste", "6 épisodes courts", "24 extraits", "40 photographies", "1 guide éditorial"],
      constraints: ["Droits validés", "Sous-titres FR/EN", "Formats 16:9, 4:5 et 9:16"],
      image: neutralStudioPortrait,
    },
    {
      id: "16-references",
      type: "references",
      eyebrow: "Direction visuelle",
      title: "Des références pour cadrer, jamais pour copier",
      references: [
        { title: "Matière franche", reason: "Des textures lisibles, photographiées sans surenchère.", source: "Principe visuel" },
        { title: "Présence réelle", reason: "Des personnes absorbées par leur geste, jamais mises en scène comme des modèles.", source: "Direction humaine" },
        { title: "Échelle révélée", reason: "Le détail prépare le plan large et lui donne davantage de poids.", source: "Rythme de cadrage" },
        { title: "Signe constant", reason: "Un motif graphique discret relie les formats sans les uniformiser.", source: "Système de marque" },
      ],
      note: "La sélection finale sera sourcée, créditée et validée avant production.",
    },
    {
      id: "17-merci",
      type: "thank-you",
      tone: "accent",
      title: "Construisons un récit à la hauteur du travail.",
      message: "Nous proposons de commencer par une session de cadrage de deux heures avec les personnes qui portent la vision et les preuves.",
      contact: { name: "Contact Démo", role: "Direction créative", email: "bonjour@studio-demo.invalid", website: "https://studio-demo.invalid" },
      nextStep: "Prochaine étape: valider l'angle et les interlocuteurs.",
    },
    {
      id: "18-signature",
      type: "lockup",
      tone: "ink",
      title: "La précision en mouvement",
      statement: "Une proposition de plateforme narrative et de films pour Prospect Démo.",
      client: "Prospect Démo",
      studio: "Studio Démo",
      relationshipLabel: "Proposition indépendante pour Prospect Démo, par Studio Démo",
      legal: "Document de démonstration • 2026",
    },
  ] satisfies readonly DossierSlide[]).map(withExampleClaims),
} satisfies Dossier;
